#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.7
# from Racc grammer file "".
#

require 'racc/parser.rb'

#
# generated by racc
#
require_relative 'lexer'

module Noscript
  class Parser < Racc::Parser

module_eval(<<'...end noscript.y/module_eval...', 'noscript.y', 239)

include AST

def parse(code)
  scan_str(code)
end

...end noscript.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    -1,   117,    32,   102,    33,     5,    17,    18,    22,    23,
    24,    30,    60,     5,    -5,    31,    32,    -5,    33,    -5,
    17,    18,    22,    23,    24,    30,    -5,   100,     5,    31,
     6,    16,    30,    25,    27,   129,   101,    29,     6,    36,
    49,    47,    48,    51,    -5,    16,    95,    25,    27,     5,
    32,    29,    33,     6,    17,    18,    22,    23,    24,    30,
    32,    66,    33,    31,    17,    18,    22,    23,    24,    30,
    96,    65,   107,    31,     6,    51,    94,    30,   125,    16,
     5,    25,    27,   110,    70,    29,   109,   124,    36,    16,
     5,    25,    27,    30,    32,    29,    33,    30,    17,    18,
    22,    23,    24,    30,    32,     6,    33,    31,    17,    18,
    22,    23,    24,    30,    91,     6,    65,    31,    36,    30,
    47,    48,    30,    16,     5,    25,    27,   103,    92,    29,
    36,   126,    36,    16,    34,    25,    27,   114,    32,    29,
    33,     5,    17,    18,    22,    23,    24,    30,   nil,     6,
    32,    31,    33,    59,    17,    18,    22,    23,    24,    30,
   nil,   nil,   nil,    31,   nil,   nil,     6,    16,   nil,    25,
    27,   nil,   nil,    29,   nil,   nil,   nil,   -33,   nil,    16,
   nil,    25,    27,   -33,    32,    29,    33,     5,    17,    18,
    22,    23,    24,    30,    32,   nil,    33,    31,    17,    18,
    22,    23,    24,    30,   nil,   nil,    36,    31,    47,    48,
    45,    46,     6,    16,     5,    25,    27,   nil,   nil,    29,
   nil,   123,   nil,    16,   nil,    25,    27,   nil,    32,    29,
    33,    59,    17,    18,    22,    23,    24,    30,    32,     6,
    33,    31,    17,    18,    22,    23,    24,    30,   nil,   nil,
    36,    31,    47,    48,    45,    46,   nil,    16,   nil,    25,
    27,   nil,   nil,    29,   nil,   nil,   nil,    16,   nil,    25,
    27,   nil,    32,    29,    33,   nil,    17,    18,    22,    23,
    24,    30,    32,   nil,    33,    31,    17,    18,    22,    23,
    24,    30,   nil,   nil,    36,    31,    47,    48,    45,    46,
   nil,    16,   nil,    25,    27,   nil,   nil,    29,   nil,   nil,
   nil,    16,   nil,    25,    27,   nil,    32,    29,    33,   nil,
    17,    18,    22,    23,    24,    30,   nil,   nil,    32,    31,
    33,     5,    17,    18,    22,    23,    24,    30,   nil,   nil,
   nil,    31,   nil,   nil,   nil,    16,   nil,    25,    27,   nil,
    36,    29,    47,    48,    45,    46,     6,    16,   nil,    25,
    27,   nil,    32,    29,    33,     5,    17,    18,    22,    23,
    24,    30,    32,   nil,    33,    31,    17,    18,    22,    23,
    24,    30,   nil,   nil,   nil,    31,   nil,   nil,   nil,   nil,
     6,    16,   nil,    25,    27,   nil,   nil,    29,   nil,   nil,
   nil,    16,    87,    25,    27,   nil,    32,    29,    33,   nil,
    17,    18,    22,    23,    24,    30,    32,   nil,    33,    31,
    17,    18,    22,    23,    24,    30,   nil,   nil,   nil,    31,
   nil,   nil,   nil,   nil,   nil,    16,   nil,    25,    27,   nil,
   nil,    29,   nil,   nil,   nil,    16,   nil,    25,    27,   nil,
    32,    29,    33,   nil,    17,    18,    22,    23,    24,    30,
    32,   nil,    33,    31,    17,    18,    22,    23,    24,    30,
   nil,   nil,   nil,    31,   nil,   nil,   nil,   nil,   nil,    16,
   nil,    25,    27,   nil,   nil,    29,   nil,   nil,   nil,    16,
   nil,    25,    27,   nil,    32,    29,    33,   nil,    17,    18,
    22,    23,    24,    30,    32,   nil,    33,    31,    17,    18,
    22,    23,    24,    30,   nil,   nil,   nil,    31,   nil,   nil,
   nil,   nil,   nil,    16,   nil,    25,    27,   nil,   nil,    29,
   nil,   nil,   nil,    16,   nil,    25,    27,   nil,    32,    29,
    33,   nil,    17,    18,    22,    23,    24,    30,    32,   nil,
    33,    31,    17,    18,    22,    23,    24,    30,   nil,   nil,
   nil,    31,   nil,   nil,   nil,   nil,   nil,    16,   nil,    25,
    27,   nil,   nil,    29,   nil,   nil,   nil,    16,   nil,    25,
    27,   nil,    32,    29,    33,   nil,    17,    18,    22,    23,
    24,    30,    32,   nil,    33,    31,    17,    18,    22,    23,
    24,    30,   nil,   nil,   nil,    31,   nil,   nil,   nil,   nil,
   nil,    16,   nil,    25,    27,   nil,   nil,    29,   nil,   nil,
   nil,    16,   nil,    25,    27,   nil,    32,    29,    33,   nil,
    17,    18,    22,    23,    24,    30,    32,   nil,    33,    31,
    17,    18,    22,    23,    24,    30,   nil,   nil,   nil,    31,
   nil,   nil,   nil,   nil,   nil,    16,   nil,    25,    27,   nil,
   nil,    29,   nil,   nil,   nil,    16,   nil,    25,    27,   nil,
    32,    29,    33,     5,    17,    18,    22,    23,    24,    30,
   nil,   nil,    36,    31,    47,    48,    45,    46,    41,    42,
    43,    44,    39,    40,    38,    37,   nil,     5,     6,    16,
   nil,    25,    27,   nil,   nil,    29,    36,   nil,    47,    48,
    45,    46,    41,    42,    43,    44,    39,    40,    38,    37,
    97,   nil,     6,   nil,   nil,   nil,   nil,   nil,   nil,    36,
   nil,    47,    48,    45,    46,    41,    42,    43,    44,    39,
    40,    38,    37,    36,   nil,    47,    48,    45,    46,    41,
    42,    43,    44,    39,    40,    38,    37,   nil,   nil,   nil,
    36,    89,    47,    48,    45,    46,    41,    42,    43,    44,
    39,    40,    38,    37,    36,   nil,    47,    48,    45,    46,
    41,    42,    43,    44,    39,    40,    38,    37,    36,   nil,
    47,    48,    45,    46,    41,    42,    43,    44,    39,    40,
    38,    37,    36,   nil,    47,    48,    45,    46,    41,    42,
    43,    44,    39,    40,    38,    37,    36,   nil,    47,    48,
    45,    46,    41,    42,    43,    44,    39,    40,    38,    37,
    36,   nil,    47,    48,    45,    46,    41,    42,    43,    44,
    39,    40,    38,    37,    36,   nil,    47,    48,    45,    46,
    41,    42,    43,    44,    39,    40,    38,    37,    36,   nil,
    47,    48,    45,    46,    41,    42,    43,    44,    39,    40,
    38,    37,    36,   nil,    47,    48,    45,    46,    41,    42,
    43,    44,    39,    40,    38,    37,    36,   nil,    47,    48,
    45,    46,    41,    42,    43,    44,    39,    40,    38,    36,
   nil,    47,    48,    45,    46,    41,    42,    43,    44,    39,
    40,    36,   nil,    47,    48,    45,    46,    41,    42,    43,
    44,    36,   nil,    47,    48,    45,    46,    41,    42,    43,
    44 ]

racc_action_check = [
     0,   102,     0,    61,     0,     0,     0,     0,     0,     0,
     0,     0,    27,   125,    35,     0,    35,    35,    35,    35,
    35,    35,    35,    35,    35,    35,    35,    61,   128,    35,
     0,     0,    25,     0,     0,   128,    61,     0,   125,    81,
    15,    81,    81,    15,    35,    35,    56,    35,    35,     2,
    59,    35,    59,   128,    59,    59,    59,    59,    59,    59,
   110,    29,   110,    59,   110,   110,   110,   110,   110,   110,
    56,    28,    72,   110,     2,    72,    56,    28,   119,    59,
   119,    59,    59,    88,    34,    59,    88,   119,    67,   110,
    53,   110,   110,    91,   107,   110,   107,    36,   107,   107,
   107,   107,   107,   107,    16,   119,    16,   107,    16,    16,
    16,    16,    16,    16,    53,    53,   100,    16,    82,    65,
    82,    82,   100,   107,   120,   107,   107,    63,    55,   107,
    84,   120,    83,    16,     1,    16,    16,    95,   106,    16,
   106,   106,   106,   106,   106,   106,   106,   106,   nil,   120,
    26,   106,    26,    26,    26,    26,    26,    26,    26,    26,
   nil,   nil,   nil,    26,   nil,   nil,   106,   106,   nil,   106,
   106,   nil,   nil,   106,   nil,   nil,   nil,    26,   nil,    26,
   nil,    26,    26,    26,   105,    26,   105,   105,   105,   105,
   105,   105,   105,   105,   103,   nil,   103,   105,   103,   103,
   103,   103,   103,   103,   nil,   nil,    78,   103,    78,    78,
    78,    78,   105,   105,   111,   105,   105,   nil,   nil,   105,
   nil,   111,   nil,   103,   nil,   103,   103,   nil,    96,   103,
    96,    96,    96,    96,    96,    96,    96,    96,    31,   111,
    31,    96,    31,    31,    31,    31,    31,    31,   nil,   nil,
    80,    31,    80,    80,    80,    80,   nil,    96,   nil,    96,
    96,   nil,   nil,    96,   nil,   nil,   nil,    31,   nil,    31,
    31,   nil,    32,    31,    32,   nil,    32,    32,    32,    32,
    32,    32,    33,   nil,    33,    32,    33,    33,    33,    33,
    33,    33,   nil,   nil,    79,    33,    79,    79,    79,    79,
   nil,    32,   nil,    32,    32,   nil,   nil,    32,   nil,   nil,
   nil,    33,   nil,    33,    33,   nil,    92,    33,    92,   nil,
    92,    92,    92,    92,    92,    92,   nil,   nil,   127,    92,
   127,   127,   127,   127,   127,   127,   127,   127,   nil,   nil,
   nil,   127,   nil,   nil,   nil,    92,   nil,    92,    92,   nil,
    77,    92,    77,    77,    77,    77,   127,   127,   nil,   127,
   127,   nil,    90,   127,    90,    90,    90,    90,    90,    90,
    90,    90,    51,   nil,    51,    90,    51,    51,    51,    51,
    51,    51,   nil,   nil,   nil,    51,   nil,   nil,   nil,   nil,
    90,    90,   nil,    90,    90,   nil,   nil,    90,   nil,   nil,
   nil,    51,    51,    51,    51,   nil,    38,    51,    38,   nil,
    38,    38,    38,    38,    38,    38,    39,   nil,    39,    38,
    39,    39,    39,    39,    39,    39,   nil,   nil,   nil,    39,
   nil,   nil,   nil,   nil,   nil,    38,   nil,    38,    38,   nil,
   nil,    38,   nil,   nil,   nil,    39,   nil,    39,    39,   nil,
    40,    39,    40,   nil,    40,    40,    40,    40,    40,    40,
    41,   nil,    41,    40,    41,    41,    41,    41,    41,    41,
   nil,   nil,   nil,    41,   nil,   nil,   nil,   nil,   nil,    40,
   nil,    40,    40,   nil,   nil,    40,   nil,   nil,   nil,    41,
   nil,    41,    41,   nil,    42,    41,    42,   nil,    42,    42,
    42,    42,    42,    42,    43,   nil,    43,    42,    43,    43,
    43,    43,    43,    43,   nil,   nil,   nil,    43,   nil,   nil,
   nil,   nil,   nil,    42,   nil,    42,    42,   nil,   nil,    42,
   nil,   nil,   nil,    43,   nil,    43,    43,   nil,    44,    43,
    44,   nil,    44,    44,    44,    44,    44,    44,    45,   nil,
    45,    44,    45,    45,    45,    45,    45,    45,   nil,   nil,
   nil,    45,   nil,   nil,   nil,   nil,   nil,    44,   nil,    44,
    44,   nil,   nil,    44,   nil,   nil,   nil,    45,   nil,    45,
    45,   nil,    46,    45,    46,   nil,    46,    46,    46,    46,
    46,    46,    47,   nil,    47,    46,    47,    47,    47,    47,
    47,    47,   nil,   nil,   nil,    47,   nil,   nil,   nil,   nil,
   nil,    46,   nil,    46,    46,   nil,   nil,    46,   nil,   nil,
   nil,    47,   nil,    47,    47,   nil,    48,    47,    48,   nil,
    48,    48,    48,    48,    48,    48,    49,   nil,    49,    48,
    49,    49,    49,    49,    49,    49,   nil,   nil,   nil,    49,
   nil,   nil,   nil,   nil,   nil,    48,   nil,    48,    48,   nil,
   nil,    48,   nil,   nil,   nil,    49,   nil,    49,    49,   nil,
    37,    49,    37,    68,    37,    37,    37,    37,    37,    37,
   nil,   nil,    68,    37,    68,    68,    68,    68,    68,    68,
    68,    68,    68,    68,    68,    68,   nil,    69,    68,    37,
   nil,    37,    37,   nil,   nil,    37,    69,   nil,    69,    69,
    69,    69,    69,    69,    69,    69,    69,    69,    69,    69,
    58,   nil,    69,   nil,   nil,   nil,   nil,   nil,   nil,    58,
   nil,    58,    58,    58,    58,    58,    58,    58,    58,    58,
    58,    58,    58,    52,   nil,    52,    52,    52,    52,    52,
    52,    52,    52,    52,    52,    52,    52,   nil,   nil,   nil,
    71,    52,    71,    71,    71,    71,    71,    71,    71,    71,
    71,    71,    71,    71,   122,   nil,   122,   122,   122,   122,
   122,   122,   122,   122,   122,   122,   122,   122,    98,   nil,
    98,    98,    98,    98,    98,    98,    98,    98,    98,    98,
    98,    98,     3,   nil,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,   113,   nil,   113,   113,
   113,   113,   113,   113,   113,   113,   113,   113,   113,   113,
   118,   nil,   118,   118,   118,   118,   118,   118,   118,   118,
   118,   118,   118,   118,   121,   nil,   121,   121,   121,   121,
   121,   121,   121,   121,   121,   121,   121,   121,    86,   nil,
    86,    86,    86,    86,    86,    86,    86,    86,    86,    86,
    86,    86,    85,   nil,    85,    85,    85,    85,    85,    85,
    85,    85,    85,    85,    85,    85,    73,   nil,    73,    73,
    73,    73,    73,    73,    73,    73,    73,    73,    73,    74,
   nil,    74,    74,    74,    74,    74,    74,    74,    74,    74,
    74,    76,   nil,    76,    76,    76,    76,    76,    76,    76,
    76,    75,   nil,    75,    75,    75,    75,    75,    75,    75,
    75 ]

racc_action_pointer = [
     0,   134,    44,   788,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    12,   102,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    21,   148,     7,    66,    56,
   nil,   236,   270,   280,    84,    14,    86,   668,   404,   414,
   448,   458,   492,   502,   536,   546,   580,   590,   624,   634,
   nil,   370,   729,    85,   nil,   100,    41,   nil,   715,    48,
   nil,    -2,   nil,    91,   nil,   108,   nil,    74,   668,   692,
   nil,   746,    44,   872,   885,   907,   897,   336,   192,   280,
   236,    25,   104,   118,   116,   858,   844,   nil,    54,   nil,
   360,    82,   314,   nil,   nil,   102,   226,   nil,   774,   nil,
   111,   nil,   -37,   192,   nil,   182,   136,    92,   nil,   nil,
    58,   209,   nil,   802,   nil,   nil,   nil,   nil,   816,    75,
   119,   830,   760,   nil,   nil,     8,   nil,   326,    23,   nil ]

racc_action_default = [
   -53,   -82,    -2,    -3,    -6,    -7,    -8,    -9,   -10,   -11,
   -12,   -13,   -14,   -15,   -16,   -17,   -53,   -19,   -20,   -21,
   -22,   -23,   -24,   -25,   -26,   -74,   -53,   -29,   -40,   -46,
   -50,   -53,   -53,   -53,   -82,   -53,   -82,   -53,   -53,   -53,
   -53,   -53,   -53,   -53,   -53,   -53,   -53,   -53,   -53,   -53,
   -55,   -53,   -82,   -82,   -75,   -78,   -82,   -34,   -36,   -53,
   -30,   -82,   -41,   -82,   -44,   -82,   -47,   -73,   -82,   -82,
   130,    -4,   -54,   -61,   -62,   -63,   -64,   -65,   -66,   -67,
   -68,   -69,   -70,   -71,   -72,   -51,   -59,   -57,   -82,   -18,
   -53,   -82,   -53,   -28,   -31,   -82,   -53,   -38,   -37,   -39,
   -82,   -48,   -82,   -53,   -45,   -53,   -53,   -53,   -56,   -58,
   -53,   -82,   -76,   -77,   -32,   -35,   -42,   -49,   -43,   -82,
   -82,   -52,   -60,   -27,   -79,   -82,   -81,   -53,   -82,   -80 ]

racc_goto_table = [
     2,    52,    35,    62,    57,    54,    50,    93,    61,    99,
    55,    58,    56,    64,    53,    88,    67,    68,    69,     1,
    71,    72,    73,    74,    75,    76,    77,    78,    79,    80,
    81,    82,    83,    84,    85,   nil,    86,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    98,   nil,   nil,   nil,   nil,   nil,
   104,   nil,   nil,    90,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   108,   nil,   nil,   nil,   nil,   105,   106,
   nil,   112,   nil,   nil,   115,   116,    55,   113,   nil,   nil,
   nil,    58,   nil,   nil,   nil,    64,   nil,   nil,   118,   nil,
   111,   nil,   121,   nil,   nil,   122,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   119,   120,   nil,   nil,   nil,
   nil,    35,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    35,
    35,   nil,   nil,   nil,   nil,   127,   nil,   128,    35 ]

racc_goto_check = [
     2,     3,     4,    25,    21,    29,    27,    20,    23,    24,
    13,     3,    19,    13,    17,    28,     3,     3,     3,     1,
     3,    13,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,   nil,     3,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     3,   nil,   nil,   nil,   nil,   nil,
    13,   nil,   nil,     4,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    27,   nil,   nil,   nil,   nil,     4,     4,
   nil,    29,   nil,   nil,    21,    25,    13,     3,   nil,   nil,
   nil,     3,   nil,   nil,   nil,    13,   nil,   nil,     3,   nil,
     2,   nil,     3,   nil,   nil,     3,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     2,     2,   nil,   nil,   nil,
   nil,     4,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     4,
     4,   nil,   nil,   nil,   nil,     4,   nil,     2,     4 ]

racc_goto_pointer = [
   nil,    19,     0,   -15,     0,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   -15,   nil,   nil,   nil,   -11,   nil,   -14,
   -49,   -22,   nil,   -20,   -52,   -25,   nil,    -9,   -36,   -20 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     7,     8,     9,    10,    11,
    12,    13,    14,    15,    19,    20,    21,   nil,    26,   nil,
   nil,   nil,    28,   nil,   nil,   nil,    63,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 40, :_reduce_1,
  1, 40, :_reduce_2,
  1, 41, :_reduce_3,
  3, 41, :_reduce_4,
  2, 41, :_reduce_5,
  1, 41, :_reduce_6,
  1, 43, :_reduce_none,
  1, 43, :_reduce_none,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  3, 42, :_reduce_18,
  1, 44, :_reduce_19,
  1, 44, :_reduce_20,
  1, 44, :_reduce_21,
  1, 44, :_reduce_22,
  1, 44, :_reduce_23,
  1, 44, :_reduce_24,
  1, 44, :_reduce_25,
  1, 44, :_reduce_26,
  5, 53, :_reduce_27,
  3, 54, :_reduce_28,
  1, 57, :_reduce_none,
  2, 57, :_reduce_none,
  1, 59, :_reduce_none,
  2, 59, :_reduce_none,
  0, 58, :_reduce_33,
  1, 58, :_reduce_34,
  3, 58, :_reduce_35,
  1, 60, :_reduce_36,
  2, 60, :_reduce_37,
  2, 60, :_reduce_38,
  3, 55, :_reduce_39,
  0, 62, :_reduce_40,
  1, 62, :_reduce_41,
  3, 62, :_reduce_42,
  3, 64, :_reduce_43,
  1, 65, :_reduce_none,
  2, 65, :_reduce_45,
  1, 61, :_reduce_none,
  2, 61, :_reduce_none,
  1, 63, :_reduce_none,
  2, 63, :_reduce_none,
  1, 52, :_reduce_50,
  3, 48, :_reduce_51,
  5, 46, :_reduce_52,
  0, 51, :_reduce_none,
  3, 51, :_reduce_54,
  2, 45, :_reduce_55,
  4, 45, :_reduce_56,
  2, 66, :_reduce_57,
  3, 66, :_reduce_58,
  1, 67, :_reduce_59,
  3, 67, :_reduce_60,
  3, 47, :_reduce_61,
  3, 47, :_reduce_62,
  3, 47, :_reduce_63,
  3, 47, :_reduce_64,
  3, 47, :_reduce_65,
  3, 47, :_reduce_66,
  3, 47, :_reduce_67,
  3, 47, :_reduce_68,
  3, 47, :_reduce_69,
  3, 47, :_reduce_70,
  3, 47, :_reduce_71,
  3, 47, :_reduce_72,
  2, 47, :_reduce_73,
  0, 56, :_reduce_74,
  1, 56, :_reduce_75,
  3, 56, :_reduce_76,
  3, 68, :_reduce_77,
  1, 68, :_reduce_78,
  5, 49, :_reduce_79,
  8, 49, :_reduce_80,
  5, 50, :_reduce_81 ]

racc_reduce_n = 82

racc_shift_n = 130

racc_token_table = {
  false => 0,
  :error => 1,
  :IF => 2,
  :ELSE => 3,
  :WHILE => 4,
  :NEWLINE => 5,
  :INTEGER => 6,
  :STRING => 7,
  :TRUE => 8,
  :FALSE => 9,
  :NIL => 10,
  :IDENTIFIER => 11,
  :END => 12,
  :UMINUS => 13,
  "." => 14,
  "!" => 15,
  "*" => 16,
  "/" => 17,
  "+" => 18,
  "-" => 19,
  ">" => 20,
  ">=" => 21,
  "<" => 22,
  "<=" => 23,
  "==" => 24,
  "!=" => 25,
  "&&" => 26,
  "||" => 27,
  "=" => 28,
  "," => 29,
  ";" => 30,
  "(" => 31,
  ")" => 32,
  "->" => 33,
  "[" => 34,
  "]" => 35,
  ":" => 36,
  "{" => 37,
  "}" => 38 }

racc_nt_base = 39

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "NEWLINE",
  "INTEGER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "END",
  "UMINUS",
  "\".\"",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"==\"",
  "\"!=\"",
  "\"&&\"",
  "\"||\"",
  "\"=\"",
  "\",\"",
  "\";\"",
  "\"(\"",
  "\")\"",
  "\"->\"",
  "\"[\"",
  "\"]\"",
  "\":\"",
  "\"{\"",
  "\"}\"",
  "$start",
  "Root",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Call",
  "SlotAssign",
  "Operator",
  "LocalAssign",
  "If",
  "While",
  "SlotGet",
  "Identifier",
  "Function",
  "Array",
  "Tuple",
  "ParamList",
  "LBracket",
  "ArrayList",
  "RBracket",
  "ArrayListElement",
  "LBrace",
  "TupleList",
  "RBrace",
  "TupleListElement",
  "TupleKey",
  "ArgListWithParens",
  "ArgList",
  "Parameter" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'noscript.y', 33)
  def _reduce_1(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 34)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 39)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 40)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 42)
  def _reduce_5(val, _values, result)
     result = val[0].is_a?(Nodes) ? val[0] : Nodes.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 43)
  def _reduce_6(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

module_eval(<<'.,.,', 'noscript.y', 63)
  def _reduce_18(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 68)
  def _reduce_19(val, _values, result)
     result = IntegerNode.new(val[0]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 69)
  def _reduce_20(val, _values, result)
     result = StringNode.new(val[0]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 70)
  def _reduce_21(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 71)
  def _reduce_22(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 72)
  def _reduce_23(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 73)
  def _reduce_24(val, _values, result)
     result = TrueNode.new; result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 74)
  def _reduce_25(val, _values, result)
     result = FalseNode.new; result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 75)
  def _reduce_26(val, _values, result)
     result = NilNode.new; result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 86)
  def _reduce_27(val, _values, result)
     result = FunctionNode.new(val[1], val[3]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 90)
  def _reduce_28(val, _values, result)
     result = ArrayNode.new(val[1]); result.pos(filename, lineno)
    result
  end
.,.,

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

module_eval(<<'.,.,', 'noscript.y', 104)
  def _reduce_33(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 105)
  def _reduce_34(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 106)
  def _reduce_35(val, _values, result)
     result = val[0] += [val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 110)
  def _reduce_36(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 111)
  def _reduce_37(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 112)
  def _reduce_38(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 116)
  def _reduce_39(val, _values, result)
     result = TupleNode.new(val[1]); result.pos(filename, lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 120)
  def _reduce_40(val, _values, result)
     result = {} 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 121)
  def _reduce_41(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 122)
  def _reduce_42(val, _values, result)
     result = val[0].merge!(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 126)
  def _reduce_43(val, _values, result)
     result = { val[0] => val[2] } 
    result
  end
.,.,

# reduce 44 omitted

module_eval(<<'.,.,', 'noscript.y', 131)
  def _reduce_45(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

module_eval(<<'.,.,', 'noscript.y', 145)
  def _reduce_50(val, _values, result)
     result = IdentifierNode.new(val[0]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 150)
  def _reduce_51(val, _values, result)
     result = LocalAssignNode.new(val[0], val[2]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 155)
  def _reduce_52(val, _values, result)
     result = SlotAssignNode.new(val[0], val[2], val[4]); result.pos(filename, lineno) 
    result
  end
.,.,

# reduce 53 omitted

module_eval(<<'.,.,', 'noscript.y', 161)
  def _reduce_54(val, _values, result)
     result = SlotGetNode.new(val[0], val[2]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 167)
  def _reduce_55(val, _values, result)
     result = CallNode.new(nil, val[0], val[1]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 170)
  def _reduce_56(val, _values, result)
     result = CallNode.new(val[0], val[2], val[3]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 174)
  def _reduce_57(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 175)
  def _reduce_58(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 179)
  def _reduce_59(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 180)
  def _reduce_60(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 185)
  def _reduce_61(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 186)
  def _reduce_62(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 187)
  def _reduce_63(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 188)
  def _reduce_64(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 189)
  def _reduce_65(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 190)
  def _reduce_66(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 191)
  def _reduce_67(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 192)
  def _reduce_68(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 195)
  def _reduce_69(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]); result.pos(filename, lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 196)
  def _reduce_70(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]); result.pos(filename, lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 197)
  def _reduce_71(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]); result.pos(filename, lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 198)
  def _reduce_72(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]); result.pos(filename, lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 200)
  def _reduce_73(val, _values, result)
     result = CallNode.new(val[1], val[0], []); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 204)
  def _reduce_74(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 205)
  def _reduce_75(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 206)
  def _reduce_76(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 210)
  def _reduce_77(val, _values, result)
     result = ParameterNode.new(val[0], val[2]); result.pos(filename, lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 211)
  def _reduce_78(val, _values, result)
     result = ParameterNode.new(val[0]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 217)
  def _reduce_79(val, _values, result)
     result = IfNode.new(val[1], val[3], nil); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 222)
  def _reduce_80(val, _values, result)
     result = IfNode.new(val[1], val[3], val[6]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'noscript.y', 228)
  def _reduce_81(val, _values, result)
     result = WhileNode.new(val[1], val[3]); result.pos(filename, lineno) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Noscript


